### ISSUE TITLE
Chunk.modules has been deprecated in Webpack 3.x

### ISSUE THREAD

**Issue by justrhysism** [adventure-yunfei/md5-hash-webpack-plugin#1]
https://github.com/adventure-yunfei/md5-hash-webpack-plugin/blob/master/index.js#L38

> (node:63912) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

**Comment by adventure-yunfei** [comment]
Need compatible fix

**Comment by adventure-yunfei** [comment]
fixed.
